services:

  backend:

    build: ./backend

    container_name: backend

    ports:

      - "8080:8080"

    environment:

      MONGO_DATABASE: ${MONGO_DATABASE}

      MONGO_URI: ${MONGO_URI}


  frontend:

    build: ./frontend

    container_name: frontend

    ports:

      - "3000:3000"
  